app/assets/stylesheets/shame.css.scss
app/helpers/application_helper.rb
app/views/layouts/application.html.haml
config/initializers/version_info.rb

Please don't merge until @mikepea has had a chance to ensure that the META file in question is, in fact JSON.

Added a hidden link to the current commit to the body of the page.

---

app/assets/stylesheets/shame.css.scss
app/helpers/application_helper.rb

Sorry, this should have been included with the previous commit.

Remove unused version helper code

---

README.md

- Correct a load of stuff
- Improve instructions on updating prison data

Upates to README

---

Gemfile.lock
app/assets/stylesheets/main.css.sass
app/views/deferred/confirmations/show.html.haml

- info on closed visits
- info on parent permission letters
- styling to support blockquotes written in Markdown

Update digital comms with latest two features

---

app/controllers/deferred/confirmations_controller.rb
app/models/visit.rb
app/views/prison_mailer/booking_cancellation_receipt_email.text.erb
spec/mailers/prison_mailer_spec.rb
spec/spec_helper.rb

Visit cancellation receipt contains VO number for reference.

---

app/views/content/_id_STI.md

Amends made:
- Rent book change to Tenancy agreement.
- Benefit book change to  Benefit letters
- Cheque book change to Credit or debit card with bank statement
- Proof of address is needed with all documents.

Amends to Styal ID Requirements

---

config/prison_data_production.yml
config/prison_data_staging.yml

Wetherby - Add Wed eve slot

---

app/assets/javascripts/metrics.js
app/assets/stylesheets/metrics.css.scss
app/controllers/metrics_controller.rb
app/views/metrics/fortnightly.html.haml
app/views/metrics/fortnightly_performance.html.haml
config/routes.rb
lib/fortnightly_performance_report.rb

Nice, fortnightly performance metrics.

---

config/prison_data_production.yml
config/prison_data_staging.yml

Change of times to 15-18yrs and 18-21yrs prisons
Mon -> Sun
2 ->4pm

Hindley time changes

---

config/prison_data_production.yml
config/prison_data_staging.yml

Winchester - April 3rd
Warren Hill - April 3rd

Blocked dates for Easter

---

app/controllers/ping_controller.rb
config/routes.rb

Using format shared across other projects to display build information.
Objective: We should be able to monitor current version / release id on PVB project. 
@ashb pointed me to PQ project - https://github.com/ministryofjustice/parliamentary-questions/blob/dev/app/controllers/ping_controller.rb and proposed to follow that pattern.

Added ping controller to display build / release information

---

Gemfile
README.md
circle.yml
test.txt

* make gemfile not bother installing the private repo if running in CI 
* remove dummy file added earlier
* update README.md to use build badge from circleci

Add Circle CI for pull request building

---

app/views/feedbacks/_form.html.haml

Experiment 1: Outcome B is preferrable.

---

app/controllers/deferred/slots_controller.rb
app/controllers/instant/slots_controller.rb

This is alnost certainly not the right way of doing the fix, but it
works and means we can book visits again.
Whithout this fix we were getting no slots returned.

HOT FIX: Instantiate the new Schedule object correctly so we can book again

---

README.md

I've tried to improve the README on how to use the `adult_age` parameter. 
Merge this if you think it's clear.

Improve the explanation of the adult_age config

---

.gitignore
Gemfile
Gemfile.lock
config/database.yml
lib/tasks/quiet.rake
spec/spec_helper.rb

This contains a few things to improve my experience of working on this project.
* Changes the local database configuration slightly in order to permit the use of PostgreSQL peer authentication (so that the specs run on Linux without additional configuration). I don't believe that this will cause any problems, as this is the configuration used in other projects.
* Silences the useless list of all spec files vomited out when running `rake`. This makes it easier to see what's actually happening.
* Adds Simplecov to measure how much of the codebase is not exercised when running tests, so that we can identify and mitigate risks when making changes.

Improve environment

---

README.md

Please see note in README for explanation.

Explain root of app in README

---

README.md

Make all "notes" consistent formatting throughout README.
Apologies, this was missed in the previous commit.

Correct formatting of "Note" in README

---

spec/features/datepicker_spec.rb

The specs should pass every day of the year.

Make specs work when month starts on Monday

---

spec/lib/schedule_spec.rb

We shouldn't have to do date maths in our head to understand the tests, so remove the magic numbers. 
It also turns out that the code doesn't behave at all as it should, so this change is purely to clarify what the code *actually* does. That way, when we come to fix the behaviour in future there's a good example of how to communicate and test that change.
Also clarify some parameters and make date construction consistent.

Clarify intent of schedule tests

---

config/prison_data_production.yml
config/prison_data_staging.yml

Don't launch till Monday ahead of communicated start date of Tuesday 4th August.
Change the contact email from maildrop to APVU before launch.

Create Stafford booking slots

---

config/prison_data_production.yml
config/prison_data_staging.yml

Visit time has been changed on Aug 31st to 13:45 - 16:00.

Lindholme - Visit time change for Aug 31st

---

config/prison_data_production.yml
config/prison_data_staging.yml

Highpoint called and urgently requested that we add their Monday slot back for the August bank holiday.

Add August bank holiday slots to Highpoint South

---

app/models/concerns/person.rb
app/models/deferred/visitor.rb
app/models/prisoner.rb
app/models/visitor.rb
app/services/age_calculator.rb
config/locales/en.yml
lib/age_validator.rb
lib/email_validator.rb
lib/visitors_manipulator.rb
spec/controllers/deferred/visitors_details_controller_spec.rb
spec/controllers/feedbacks_controller_spec.rb
spec/controllers/instant/visitors_details_controller_spec.rb
spec/features/datepicker_spec.rb
spec/features/visitor_information_page_spec.rb
spec/lib/email_validator_spec.rb
spec/models/deferred/visitor_spec.rb
spec/models/feedback_spec.rb
spec/models/instant/visitor_spec.rb
spec/models/prisoner_spec.rb
spec/services/age_calculator_spec.rb
spec/spec_helper.rb
spec/support/visitor_support.rb
spec/support/visitors_details_support.rb

This makes various improvements to the way that the visitor model and validations work and are tested, and corrects age calculation (as this was flagged by the new tests). It is intended to lay the groundwork for #276.
This is a replacement for #285, merged in error.

Improve visitor model and specs

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Did the basic installation for code climate. Added the gem file and then
added test reporter on the very first line of the spec_helper.

Report Coverage to Code Climate

---

app/assets/javascripts/shame.js
app/assets/stylesheets/application.sass
app/assets/stylesheets/survey.scss
app/views/deferred/visits/show.html.haml
app/views/shared/_survey.html.haml

This adds a temporary survey to gather more feedback for the Money to Prisoners service. 
It is essentially a duplication of PR #138 but with a new [survey](https://www.surveymonkey.com/r/PJWKMSQ).

Add temporary Money to Prisoners survey to request send page

---

config/prison_data_production.yml
config/prison_data_staging.yml

Stafford october slots

---

.rubocop_todo.yml
config/application.rb
lib/tasks/browserstack.rake
lib/tasks/maintenance.rake
spec/configuration/prison_data_spec.rb
spec/lib/prison_day_spec.rb

I am not sure, whether if I had to remove the argument or just add an `_` to indicate that it won't be used.

Fix unused block argument

---

config/prison_data_production.yml

DO NOT MERGE until 9am Tuesday 22nd Sept

Update Wandsworth email address to APVU

---

Gemfile
Gemfile.lock

If you haven't used it before, it shows a progress bar and fast-fails.
It's my personal favourite and is entirely opitional.  Per DP's comment,
I've pulled it out of another commit and PR'd it on its own.

Add the optional fuubar formatter

---

README.md

- install PhantomJS
- initialize test database

Add steps in READEME to prepare for running tests

---

README.md

As deveopers added all the required enironment variables so we can
have better developer experience

Add required environment variables

---

app/models/prisoner.rb
config/initializers/logstasher.rb

At present, we record the prison name, but those are sometimes multiple per NOMIS ID.

Record NOMIS ID in Kibana

---

db/migrate/20150429100538_fix_metrics_pending_status.rb

This was apparently removed by accident in 7a4d9a6582c95625ab85ab7f6e4aebeaf482a91a

Restore accidentally-deleted migration

---

config/prisons/WLI-wayland.yml

Remove Wednesday evening
Remove Thursday
Correct phone number

Update Wayland visit slots

---

config/prisons/KMI-kirkham.yml

Unbookable:
- Christmas Eve
- New Year's Eve
Additional:
- 23rd Dec 1315-1540
- 30th Dec 1315-1540

Update Kirkham Christmas visit slots

---

config/prisons/HOI-high-down.yml

Unbookable:
- Boxing Day
Additional:
- 21st Dec 1400-1600
- 28th Dec 1400-1600

Update High Down Christmas visit slots

---

README.md
app/models/prison.rb

This env var can be used when we want to test something locally that
will happen after 28 days.

Add Override booking window

---

spec/configuration/prison_data_spec.rb

I realised too late that number of HSE prisons due to be added over the
next couple of months was going to cause this to break.

Change warning threshold for live prison count

---

config/prisons/WSI-wormwood-scrubs.yml

DO NOT MERGE until 16:45 Tuesday 1st December

Change Wormwood Scrubs email address to APVU's

---

config/prisons/HVI-haverigg.yml

It is a bank holiday this year.

Add slot anomaly to let haverigg book the 28th

---

config/prisons/LYI-leyhill.yml

Slot anomaly:
- 27th Dec 0930-1130 and 1330-1530

Update Leyhill 27th Dec visit slots

---

config/prisons/LLI-long-lartin.yml

DO NOT MERGE
4th January launch

Update Long Lartin for HSE launch (4 Jan)

---

config/prisons/WHI-woodhill.yml

DO NOT MERGE
4th January launch

Update Woodhill prison for HSE launch (4 Jan)

---

config/prisons/WRI-whitemoor.yml

DO NOT MERGE
11th January launch

Update Whitemoor prison for HSE launch (11 Jan)
