ministryofjustice/prison-visits

app/controllers/deferred/confirmations_controller.rb, app/models/confirmation.rb, app/views/deferred/confirmations/_canned_responses.html.haml, app/views/mailers_common/_booking_confirmation.html.haml, app/views/mailers_common/_booking_confirmation.text.erb, spec/mailers/visitor_mailer_spec.rb, test/mailers/previews/mailer_preview_common.rb, test/mailers/previews/visitor_mailer_preview.rb
Add a checkbox to approved visit requests to notify visitors when the visit will be a 'closed visit'.
@jasiek please look at the [first commit](https://github.com/ministryofjustice/prison-visits/commit/17067293fa5c0ce96e73f9ae8726bd4fb56734be) first as I'm not convinced I've implemented the best way to replicate the token.
=> Closed visits 84122476

app/views/shared/visitors_details/_visitor_fields.html.haml
2014 was hard-coded into the DOB year for additional visitors year using the `max` attribute. This commit replaces that with a rolling year. And also sets the `min` attribute to a rolling 115 years back.
=> Fix additional visitors blocking DOB after 2014

app/views/visit/timeout.html.haml
I didn't feel confident about editing the link text - but as a 'nice to have' could it read: [LINK] Make a new visit request
=> Tweaked copy for error page

spec/features/datepicker_spec.rb, spec/features/visitor_information_page_spec.rb
- regroup before blocks to allow email validation to pass and fail when required
- only allow instant bookings to find one slot per day
- deferred bookings slot times needed updating
Fixes 86118980
=> Fix: feature specs fail on date picker

app/controllers/prisoner_details_controller.rb, lib/session_guard.rb
If there's no session, redirect with a timeout message on both `edit` and `update` actions.
[#88771750]
=> Better session timeout handling

Gemfile.lock, app/views/deferred/confirmations/show.html.haml
Some prisons are closed for visits on Easter bank holiday. This is now within 28 days.
This PR puts an alert on front of booking staff once they finish processing visits and asks them to get in touch if they want us to block-out any dates over Easter.
=> Add staff alert for Easter bank holiday

config/prison_data_production.yml, config/prison_data_staging.yml
May holiday time changes requested by Lindholme.
015-05-04:
- 1345-1600
2015-05-25:
- 1345-1600
=> Lindholme - May bank holiday time changes

README.md, config/prison_data_production.yml
HMP Onley have a policy of a seat for people 10 years old and over. This change limits bookings to visits of 3 ten year olds by setting the `adult_age` configuration to 10.
This change affects only one prison.
**Note:** This is the first prison to have a custom adult age since the [feature was implemented](https://github.com/ministryofjustice/prison-visits/pull/157), but I think mistakenly didn't put any of the [custom adult ages](https://github.com/ministryofjustice/prison-visits/pull/157/files#diff-0e9afe10f18cbb928426fdf3690f7b74) into production.
=> Set adult age to 10 for HMP Onley

config/prison_data_production.yml, config/prison_data_staging.yml
Haverigg contacted us to request that we lower the definition of
‘adult’ from 18 to 10 years as they are struggling with seating. This
change will ensure that less visitors attend.
=> Haverigg - changing definition of adult to 10 years old

config/prison_data_production.yml
Portland have requested that we reduce the adult age to 11 yrs due to
seating restrictions.
=> Portland - request to lower adult age to 11 years

app/controllers/heartbeat_controller.rb, spec/controllers/heartbeat_controller_spec.rb, spec/support/heartbeat_support.rb
When services we depend on are down (Sendgrid, Messagelabs, and the database), the healthcheck endpoint should return a HTTP 5XX response so that Pingdom fires alerts when things go awry.
=> Ensure healthcheck 5XXs on poor health

app/controllers/deferred/slots_controller.rb, app/helpers/visit_helper.rb
In issues #208 and #209, we see exceptions raised when there is no prison data for the prison name supplied. It's more helpful to raise an exception earlier that tells us that the key does not exist in the prison data hash.
Instead of:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
the exception raised by an unknown prison name is now:
KeyError: key not found: "bar"
This should assist us in tracking down the root cause of these errors.
=> Raise useful exception when prison not found

app/helpers/application_helper.rb, app/helpers/visit_helper.rb, app/views/content/_confirmation_page.md, app/views/content/_id_requirements.html.erb, app/views/content/_id_requirements.text.erb, app/views/mailers_common/_booking_confirmation.html.haml, app/views/mailers_common/_booking_confirmation.text.erb, config/initializers/markdown_handler.rb, config/initializers/redcarpet.rb, spec/helpers/application_helper_spec.rb, spec/helpers/visit_helper_spec.rb
The use of `lookup_context` is highly dependent on the internal workings of Rails, and makes it hard to upgrade to Rails 4.2.
We replace this with a more explicit method:
* Find the template (either specific or generic) on disk
* Return its content
* Render as Markdown if appropriate, using separate text and HTML templates
=> Decouple prison-specific ID requirements from Rails internals

app/controllers/application_controller.rb, app/controllers/deferred/confirmations_controller.rb, app/controllers/deferred/visits_controller.rb, app/controllers/instant/visits_controller.rb, app/controllers/visit_controller.rb, app/helpers/prisoner_details_helper.rb, app/helpers/visit_helper.rb, app/models/confirmation.rb, config/initializers/metrics_logger.rb, spec/controllers/deferred/confirmations_controller_spec.rb, spec/models/confirmation_spec.rb, spec/models/instant/visitor_spec.rb, spec/models/prisoner_spec.rb
* Removes some code that is never used (as established by Simplecov – see #212 – and inspection).
* Improves coverage from about 91 to 96%.
* Makes some small improvements to structure and readability where coverage was adequate to give confidence.
The most notable removal is of the legacy visit migrations. This was implemented for a structural change in December last year. Five months on, we can be confident that we won't need to process any more of these legacy requests, and this code is now superfluous.
=> Clean code and improve coverage

app/views/deferred/slots/edit.html.haml, app/views/instant/slots/edit.html.haml, spec/features/datepicker_spec.rb
`datepicker_spec` `Choosing a date in the past` failed for two reasons:
- The `Timecop.travel` call was *after* the page was rendered, so had no impact on the rendering.
- Travelling to the past resulted in cookies that expired in the past being issued to the test browser. Because the test browser doesn't respect our time-travelling, it considered these cookies expired instantly.
To avoid the session expiring, we should always travel to a suitable date in the future (a Tuesday, so we can test booking a prior working day of the week).
Also ensure we pass the server's idea of “today” to the JavaScript to avoid weird miscalculations of end-dates on the client-side.
=> Ensure datepicker specs run after 2015/06/09

Gemfile.lock
[CVE-2015-5147](https://security-tracker.debian.org/tracker/CVE-2015-5147) allows a stack overflow in header_anchor. That's bad. Don't allow that.
=> Update redcarpet to avoid CVE-2015-5147

config/environments/development.rb
Enables mail previews to be displayed when visiting `/rails/mailers` in development mode.
**N.B.** Mailer previews did appear to have worked at some point in the past for this project.
=> Enable mailer previews in development

app/helpers/visit_helper.rb, spec/features/prison_information_page_spec.rb, spec/helpers/visit_helper_spec.rb, spec/support/features_helper.rb
The `prison_name` helper method had accidentally been removed from the codebase in #213 and was causing errors when trying to render templates that require it - specifically when displaying reasons why a user cannot make a booking with a prison.
- Adds it back in with a test
- Adds a number of tests to the `/prisoner` page feature asserting the different error messages a user receives for different prison states (disabled, coming soon, IT issues)
- Refactors the feature test slightly to make it a bit more readable
=> Fixes missing `prison_name` on prisoner-details page

app/helpers/application_helper.rb, spec/helpers/visit_helper_spec.rb, spec/mailers/visitor_mailer_spec.rb
Changes the date format used by `strftime` to eliminate
date padding on single digit numerical output.
Refer to http://ruby-doc.org/core-2.2.2/Time.html#method-i-strftime
for more info.
- Before: Thursday  3 June
- After: Thursday 3 June
Double digit dates worked originally and will continue to
work as expected.
=> Remove extraneous white space on single digit dates

Gemfile.lock
Upgrade prison_staff_info to a version that removes `Cache-Control: no-cache` from static assets to avoid [an issue over HTTPS, as detailed by Microsoft](https://support.microsoft.com/en-gb/kb/323308).
[Delivers #98948456]
=> Stop old IEs choking on PDFs

lib/leaderboard_report.rb
This ensures that the list returned from the `leaderboard`
endpoint in the `GeckoboardController` is presented in the 
correct order.
The head of the list will now yield the worst performer with
each consecutive element improving.
Prior to this fix the list was returned in descending
performance order(the worst performer would be the 10th element).
=> Correct the order for 'bottom' leaderboard rankings

app/controllers/webhooks_controller.rb
6fb1abf didn't work, and failed to block postmaster@ emails because `p.from` is an instance of Mail::Address, which doesn't do string comparisons as we expected. Instead, we need to compare to
`p.from.address`.
=> Ensure replies aren't sent to postmaster@hmps

lib/prison_day.rb, spec/lib/prison_day_spec.rb
In the move to the new PrisonSchedule system (3dcea63), we lost the ability to have anomalous prison slots on bank holidays.
To fix this, we only want to consider the holiday-ness of a day when evaluating if the day has “normal” visiting slots.
=> Re-enable anomalous prison slots on bank holidays

app/views/content/_id_requirements.erb
This file is not being used `since standard_id_requirements` and `custom_id_requirements` [methods were removed](https://github.com/ministryofjustice/prison-visits/pull/214).
=> Remove dead view for ID requirements

README.md
Spotted a typographical mistake in the README.
=> Correct typo under 'Response times' in README

lib/prison_day.rb, lib/prison_schedule.rb, spec/lib/prison_schedule_spec.rb
Previously, the system calculated the confirmation date as the working day after the lead time. It should be the last day of the lead time.
For example, if a prison processes visits Monday to Friday, and Saturday is a visiting day, then it should be possible to book a visit for the coming Saturday:
Tuesday   | Make booking
Wednesday | Processing
Thursday  | Processing
Friday    | Processing & Confirmation
Saturday  | Visit
Previously, because of the extra day, the confirmation would not be sent until Monday, and visits would not be possible until Tuesday.
See https://www.pivotaltracker.com/story/show/101219102
=> Fix calculation of confirmation date

prison-visits.jmx
Load `prison-visits.jmx` into JMeter, and run it! This is configured to run against pre-production, but this can be changed by altering the domain name in User Defined Variables.
At present, the limiting factor appears to be the in-process email delivery in the final step.
=> Add JMeter load test script

app/models/prison.rb
This will assist in tracking down the reason behind 500 errors caused by `PrisonNotFound` exceptions.
=> Include name of not-found prison in error message

app/controllers/application_controller.rb, app/controllers/feedbacks_controller.rb
Fix the implementation of CSFR protection at thet Application Level by
setting `protect_from_forgery with: :exception` in the
`ApplicationController`
=> Fix CSRF protection at the ApplicationController

spec/helpers/visit_helper_spec.rb
We don't want to have to update our tests every time Rochester's visit slots change, so mock them.
Also reorder the expected slots so they match how weeks actually work.
This will fix the issues with #275.
=> Decouple Rochester slots from visit_helper_spec

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/deferred/slots_controller.rb, app/controllers/deferred/visitors_details_controller.rb, app/controllers/deferred/visits_controller.rb, app/controllers/instant/slots_controller.rb, app/controllers/instant/visitors_details_controller.rb, app/controllers/instant/visits_controller.rb, app/views/deferred/slots/edit.html.haml, config/initializers/session_store.rb, lib/sendgrid_helper.rb, spec/controllers/deferred/slots_controller_spec.rb, spec/controllers/instant/slots_controller_spec.rb, spec/features/unexpected_journey_spec.rb
This PR adds specs and fixes for journeys that are outside the expected path, i.e. where the session expires, or where the back button is used.
This seems to rule out session expiry as a cause of 500 errors, but does identify a large class of problems that can happen when a visitor jumps straight to a later page without the expected information in their session.
After the first step, the session must contain a visit, which has a prisoner, who has a prison name. Without this, the prison data cannot be retrieved and an exception results.
Now, if the session doesn't contain this information, we'll redirect the visitor back to the first step and get them to start again. This won't solve every possible 500 error, but it should make a difference.
=> Tests and fixes for unexpected journeys

Gemfile, Gemfile.lock, sidekiq-admin.ru
Sidekiq has a nice admin interface that gives us queue status, and can review errors etc.
Rather than using basic auth we are going to put this behind an OAuth2 gateway (run separately) and configured in the load-balancer to live under /sidekiq.
Although sidekiq is sinatra and could be mounted in the PVB app putting just one path behind OAuth would involve installing omniauth and we felt this was a smaller and safer change to make it happen this way. (It also means that there's less scope that a mistake in the config/routes.rb could open it up to theworld, but that was not the driving factor behind doing it this way.)
This was originally #280, but is now due for merging to master.
=> Add sidekiq web admin UI rackup script and required gems

.rubocop_todo.yml, Gemfile, Gemfile.lock, app/controllers/healthcheck_controller.rb, app/services/sendgrid_api.rb, lib/email_validator.rb, lib/sendgrid_helper.rb, spec/controllers/healthcheck_controller_spec.rb, spec/lib/email_validator_spec.rb, spec/lib/sendgrid_helper_spec.rb, spec/services/sendgrid_api_spec.rb
There exists a gem for integrating with Sendgrid's API: [sendgrid_toolkit](https://github.com/freerobby/sendgrid_toolkit). So let's not rewrite it.
For the existing API integration, this PR represents just a slight improvement in terseness, but it provides a good basis for adding new actions.
`SendgridHelper` is now `SendgridApi`, a thin layer that preserves the existing interface whilst using `sendgrid_toolkit` underneath. This is a minimal change in terms of testing and interface, but we should now be confident enough that we only test that we're using the `sendgrid_toolkit` API correctly in future.
=> Use a third-party Sendgrid API library

Gemfile
The browserstack rake task depends on RSpec & Parallel gems.
Both had been moved in a previous commit when the Gemfile was
reoriganised.
=> Fix browserstack dependency

app/controllers/healthcheck_controller.rb, app/services/healthcheck.rb, app/services/sendgrid_api.rb, config/environments/development.rb, config/environments/production.rb, config/sidekiq.yml, spec/controllers/healthcheck_controller_spec.rb, spec/services/healthcheck_spec.rb, spec/services/sendgrid_api_spec.rb
**DO NOT MERGE YET** – Waiting for PIA
* https://www.pivotaltracker.com/story/show/96673886
* https://www.pivotaltracker.com/story/show/96673592
Sending email is one of the main performance-limiting factors in this application. This set of commits configures the application to use Redis for queueing, with the Sidekiq adapter. The queues are configured via `config/sidekiq.yml`, and the remaining configuration can be done via the command-line as required. The default configuration expects a local instance of Redis on its default port. The queue can be consumed using the `sidekiq` executable:
```sh
$ bundle exec sidekiq
```
Now that we are going to send emails via queues, we don't actually care about transient unavailability of SMTP servers or the Zendesk API. Instead, we care how many items …
=> Send email and tickets outside the main request-response cycle

config/application.rb, config/environments/development.rb, config/initializers/session_store.rb, spec/configuration/session_cookie_spec.rb
Now the session timeout is 20 minutes for staging and production,
but for the development is 24 hours so its less aggressive now.
=> Make session timeout longer in development

config/routes.rb
We change route so it doesn't redirect to the live environment in the
dev environment.
=> Make `/` only route to start page on prod

smoke_test/steps/check_your_request_page.rb, smoke_test/steps/process_visit_request_page.rb, smoke_test/steps/slots_page.rb, smoke_test/steps/visitors_page.rb
This was removed from master last week.  It got missed from the smoke
tests because the branch had not been merged at the time.
=> Remove /deferred from the tested paths

smoke_test/steps/base_step.rb
This has changed the amount of time it takes for an email to get through
the system, resulting in smoke test timeouts.  This change should fix
that.
=> Change timeouts to account for sidekiq queue

spec/spec_helper.rb
Running the coverage report takes time, but is not useful when running a single spec. In order to allow faster iteration, let's skip the report when there's only one spec file to run.
This is an alternative to #348 that might be more generally useful.
=> Don't run SimpleCov for only one file

app/views/shared/visitors_details/_visitor_fields.html.haml
This was a bug, but one that wasn't visible in manual or automated testing. It is exercised by the override-email-problems branch, which was how it was discovered.
=> Ensure that variable is available to partial

.default_rubocop.yml, app/mailers/visitor_mailer.rb, app/models/feedback.rb, app/models/visitor.rb, app/services/sendgrid_api.rb, app/services/spam_and_bounce_resets.rb, app/views/shared/visitors_details/_visitor_fields.html.haml, config/locales/en.yml, lib/email_validator.rb, spec/features/datepicker_spec.rb, spec/features/override_sendgrid_spec.rb, spec/features/prison_information_page_spec.rb, spec/features/visitor_information_page_spec.rb, spec/lib/email_validator_spec.rb, spec/mailers/visitor_mailer_spec.rb, spec/poltergeist_helper.rb, spec/services/sendgrid_api_spec.rb, spec/support/features_helper.rb, spec/support/visitor_support.rb
This improves the reporting of email errors when an address has been reported by Sendgrid as having bounced or been marked as spam.
It adds a checkbox to the visitor form to allow the visitor to force acceptance of an email address that failed the Sendgrid checks. The checkbox is only displayed if validation fails for one of these two reasons. If selected, we permit the email address, and tell Sendgrid to remove the spam or bounced categorisation before sending the email.
=> Let visitors override spam/bounced email rejection

app/models/concerns/person.rb, spec/models/concerns/person_spec.rb
The maximum value for date input fields (enforced in modern browsers) was incorrectly calculated as 120 years ago from today, and not the end of the year. This meant that, for example, on 9 October, dates with a day greater than 9 or a month greater than 10 could not be entered.
=> Fix incorrect input validation on age fields

smoke_test/smoke_test.rb
This didn't break anything, as the misspelling was consistent, but it was a bit disconcerting.
=> Fix typo in smoke tests

app/assets/javascripts/application.js, app/assets/javascripts/modules/moj.form-errors.js, app/controllers/frontend_events_controller.rb, app/views/prisoner_details/_dob.html.erb, app/views/shared/visitors_details/_dob.html.erb, config/routes.rb, spec/controllers/frontend_events_controller_spec.rb
We don't have any visibility of what happens when a visitor's browser prevents them from submitting a form because an input failed validation, so we don't know when we have inadvertently locked them out.
The HTML5 form validation API exposes an 'invalid' event that we can listen for. We can then POST back to the server with some salient details (path and field name) so that we can monitor and graph these over time, and be aware of spikes that indicate when we've messed up.
Logstasher will record the parameters, and this can be viewed in Kibana with a query like:
(type:pvb AND path:"/frontend_events")
Unfortunately, PhantomJS does not respond to the 'invalid' event, so we can't actually test this except by manual means. Sad times.
=> Record an event when an input fails validation

app/mailers/prison_mailer.rb, app/mailers/visitor_mailer.rb, config/locales/en.yml, spec/controllers/confirmations_controller_spec.rb, spec/controllers/visit_controller_spec.rb, spec/controllers/visits_controller_spec.rb, spec/mailers/prison_mailer_spec.rb, spec/mailers/visitor_mailer_spec.rb
Date format changed for both 'prison_mailer' and 'visitor_mailer' to
be (full weekday name, day of the month, full month name and year).
So both of them have the same date format and give all the necessary
details
=> Change date format

app/controllers/confirmations_controller.rb, spec/controllers/confirmations_controller_spec.rb
These prison names were last changed in 2014, and we've checked the metrics and verified that these fixes are no longer used.
Whilst we may need to handle prison name changes in the future, we will do this in a better way than by dumping a hash of strings directly into the controller.
=> Remove legacy data fixes

app/services/sendgrid_api.rb
This was deleted in 9c276713 but was inadvertently reintroduced in ac7605bd.
=> Remove smtp_alive? (again!)

config/initializers/prisons.rb, spec/configuration/prison_data_spec.rb, spec/helpers/visit_helper_spec.rb, spec/mailers/concerns/visitor_mailer_shared_conditions.rb, spec/mailers/prison_mailer_spec.rb, spec/models/prisoner_spec.rb, spec/models/visit_spec.rb
It should not be sending emails to the prisons from preprod, test or
dev.  I missed this when merging prison_data_production and
prison_data_staging.  This fixes it programatically and for all prisons.
=> Prevent emails being sent outside production

config/initializers/prisons.rb
This was being selected for everything but production, but preprod, of
course, runs in production mode, so it wasn't working. This fixes that.
=> Send to maildrop in test or based on env

app/controllers/metrics_controller.rb, app/models/prison.rb, spec/models/prison_spec.rb
The metrics_controller was using Prison.nomis_ids, which exposed the
nomis_ids for all prisons, not simply the enabled ones. I believe this
was causing some cruft to appear in /metrics.  This should fix that.
=> Do not show disabled prisons in metrics

config/prisons/WYI-wetherby.yml
Unbookable - Christmas Day
Additional slots - 24th, 28th, 31st Dec and 1st Jan 1430-1630
=> Update Wetherby Christmas visit slots

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/visit.rb, app/services/visit/integrity_checker.rb, spec/models/visit_spec.rb, spec/services/visit/integrity_checker_spec.rb
We are experiencing 500 errors on the live service that *appear* to be
happening when existing visits are deserialised. Visits lose their
prisoner_name and prison.slots attributes.  This commit removes the
bulk of the Visit integrity checking logic to the model and uses
that method, `required_information?`, to call a series of logging methods
that look for missing prisoner and prison associations.  Hopefully, this
will give us some insight on where these errors are coming from.
=> Move validity check to model and log missing info

config/prisons/GTI-gartree.yml
Unbookable:
- Boxing Day
Slot anomaly:
- 28th Dec 1400-1600
=> Update Gartree Christmas visit slots

config/prisons/GNI-grendon.yml
Unbookable:
- 18th December
- Boxing Day
Updated phone number
=> Update Grendon Christmas visit slots

config/prisons/EVI-everthorpe.yml
Unbookable:
Christmas Day
Additional visits:
- 23rd December 0930-1130 and 1400-1600
=> Update Everthorpe (Humber) Christmas visit slots

config/prisons/NSI-north-sea-camp.yml
Unbookable:
- Christmas Eve
- Boxing Day
- New Year's Eve
Slot anomalies:
- 28th Dec 0900-1130 and 1330-1545
=> Update North Sea Camp Christmas visit slots

config/prisons/WLI-wayland.yml
Unbookable:
- Boxing Day
- New Year's Eve
Slot anomalies:
- 24th Dec 1400-1600
=> Update Wayland Christmas visit slots

config/prisons/LCI-leicester.yml
Unbookable
- Boxing Day
Slot anomalies:
- Christmas Eve 0900-1100 and 1415-1615
- New Year's Eve 0900-1100 and 1415-1615
=> Update Leicester Christmas visit slots

config/locales/en.yml
A visitor reported seeing `Visitors translation missing: en.activemodel.errors.models.visit.attributes.visitors.at_least_one_adult` on the live site.
=> Fix nesting of i18n YAML

app/views/confirmations/_canned_responses.html.haml, app/views/mailers_common/_booking_rejection.html.haml, app/views/mailers_common/_booking_rejection.text.erb
Problem reported by prison staff:
> We find the wording confusing on the section regarding visiting allowance. If there is still availability to use a PVO, it currently says “However, you can book a weekday visit with visiting allowance valid until ????. The visit must be TAKEN before the allowance expires.”
> 
> We think it would be clearer if it said “must be BOOKED before the allowance expires”.
=> Clarify allowance wording

lib/tasks/stats.rake
Rails comes with a predefined list of blessed directories in a big global constant that it uses to calculate statistics in `rake stats`, and will ignore custom directories like `app/validators`, `app/services` etc.
This adds these directories in the same way that RSpec does it.
=> Include custom app directories in code stats

config/prisons/LNI-low-newton.yml
Slot anomalies:
- 23rd December 1345-1545
- 28th December 1345-1545
Unbookable:
- Boxing Day
=> Update Low Newton Christmas visit slots

config/initializers/prisons.rb, config/prisons/NMI-nottingham.yml, config/prisons/WHI-woodhill.yml
By providing sensible defaults, we no longer need to put lines like `unbookable: []` in the YAML.
=> Obviate the need for empty YAML defaults

README.md
As of #527, we no longer need to put in an empty `unbookable` entry if there are no unbookable dates.
=> Remove outdated comment from README

README.md, app/controllers/start_page_controller.rb, config/application.rb, config/routes.rb, spec/controllers/start_page_controller_spec.rb
Notes
* A threshold is stored in the user's session so that they get the same experience each time (until the configured probability is altered).
* Safe to merge and deploy – the default behaviour redirects 0% of requests.
=> Redirect proportion of sessions to new app

app/controllers/prisoner_details_controller.rb, spec/controllers/start_page_controller_spec.rb
I'm using a permanent redirect to encourage browsers to cache the change. I don't foresee reverting this change.
=> Redirect remaining traffic to the new app
